# Site settings
title: Cedulio Cezar
header-img: img/home.png
email: ceduliocezar@gmail.com
copyright_name: Cedulio Cezar
description: "A"
baseurl: "ceduliocezar.github.io"
url: "http://www.ceduliocezar.com"
twitter_username: readablecoding
github_username:  ceduliocezar
email_username:  ceduliocezar@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
